### ISSUE TITLE
Gem dependencies are not listed correctly

### ISSUE THREAD

**Issue by khash** [aws/aws-sdk-rails#101]
The README states that this gem includes `aws-sdk-sesv2` but in order to use any functionality beyond the default mailed (like ListManagement), you'd need to include `gem "aws-sdk-sesv2"` in the Gemfile.

**Comment by mullermp** [comment]
What version are you using? aws-sdk-sesv2 is in the gemspec here: https://github.com/aws/aws-sdk-rails/blob/main/aws-sdk-rails.gemspec#L25 - it should be pulling this dependency.

**Comment by khash** [comment]
I'm using `3.6.4`. It might be that I'm trying to use SESv2 in a Rake task, but without adding `gem "aws-sdk-sesv2"` to the `Gemfile` `require 'aws-sdk-sesv2'` wouldn't find the library.

**Comment by mullermp** [comment]
Version 3.7.0 adds the SES v2 mailer (which would bring in the SES v2 gem). Try running `bundle update` and the latest aws-sdk-rails should pull it in.

https://github.com/aws/aws-sdk-rails/blob/main/CHANGELOG.md

**Comment by khash** [comment]
Thank you, explicitly setting the version to 3.7.0 worked. I guess other dependencies made bundler to choose the older version even when it was not specified.
