### ISSUE TITLE
Support for `ActiveJob.perform_all_later` (Rails 7.1)

### ISSUE THREAD

**Issue by gondalez** [aws/aws-sdk-rails#105]
Hi, 

Thanks for the well written gem. We have been using it for ActiveJob mainly and it has been pleasantly performant and unsurprising with our production workload 😌 🙏 

I stumbled on `ActiveJob.perform_all_later` that was [added in rails 7.1](https://www.bigbinary.com/blog/rails-7-1-adds-activejob-perform-all-later).

Are there any plans to support it in `aws-sdk-rails`?

Specifically to support creating many sqs message in a single [`SendMessageBatch`](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html) for increased throughput.

The rails PR for reference: https://github.com/rails/rails/pull/46603

**Comment by mullermp** [comment]
Thanks for opening an issue. Adding this as a feature request.
