### ISSUE TITLE
Aws::SES::Client 403 » Mailer does not raise error

### ISSUE THREAD

**Issue by jufemaiz** [aws/aws-sdk-rails#11]
Currently seeing a 403 error on Aws::SES::Client.

```
Aug 18 15:33:24 energylink-production production.log:  I, [2016-08-18T05:33:23.954349 #18197]  INFO -- : [AWS SimpleEmailService 200 1.134861 0 retries] send_raw_email(:destinations=>[EMAILS],:raw_message=>{:data=> ... (45260 bytes)>})  
Aug 18 15:33:24 production.log:  I, [2016-08-18T05:33:23.954749 #18197]  INFO -- : 
Aug 18 15:33:24 production.log:  Sent mail to  (1180.5ms)
```

My reading of the documentation is that Aws SDK should be rotating Aws::InstanceProfileCredentials automagically as required without manual intervention.

> If you're running your Ruby on Rails application on Amazon Elastic Compute Cloud, keep in mind that the AWS SDK for Ruby will automatically check Amazon EC2 instance metadata for credentials. 

http://docs.aws.amazon.com/sdkforruby/api/Aws/InstanceProfileCredentials.html
https://github.com/aws/aws-sdk-core-ruby/issues/193

**Comment by awood45** [comment]
The SDK should, and does, rotate refreshable credentials if you use one of the credential types that refreshes automatically - Instance Profile Credentials is one of those.

How are you instantiating your client? Are you doing any manual configuration of your client?

**Comment by jufemaiz** [comment]
Hi @awood45, I discovered the issue, was referencing the credentials directly instead of the credential provider in my Aws object config.

That's resolved (sorry, tore my hair out for a few hours yesterday over it), however the other issue still exists. If a mailer send fails, the mailer doesn't fail. It states that it's successful.

**Comment by awood45** [comment]
Yup, we'll look in to that now. Glad that part got resolved!

**Comment by jufemaiz** [comment]
Any thought on the error it *should* raise? There seems to be some odd ones listed here…
http://docs.aws.amazon.com/sdkforruby/api/Aws/SES/Errors.html

**Comment by awood45** [comment]
I think it should just raise whatever error occurred, or wrap it and keep the original error as a member. The issue seems to be that Rails is silently dropping the error - I'm not actually sure why that is at this point and need to investigate.

**Comment by awood45** [comment]
One question I do have, though, is how you know the failure occurred. Your log example above seems to show a 200 response from SES. Did you paste the wrong log, or did I miss something?

**Comment by awood45** [comment]
After further research, it looks like send errors are squelched by design, and that you can choose to have them raised based on a configuration setting. However, you could also check if the send succeeded using a boolean check, to avoid raising errors directly to the user. Working on an example for you.

**Comment by awood45** [comment]
So, I created an example that will always fail on delivery, because I'm using an SES account where I have to whitelist email addresses ahead of time (non-production account).

The key is in your `config/environments/development.rb` (or test or production as appropriate) file:
```ruby
config.action_mailer.raise_delivery_errors = true
```

If that line is set to true, then you'll raise the client error. If it is set to false, the error will be hidden by Rails.

**Comment by jufemaiz** [comment]
Oh sh!t. Apologies for my ineptitude :(

I checked all sorts of things without going back there :(

Sorry for time wasted ><

**Comment by awood45** [comment]
That's alright, gave me an excuse to dive in some of the Rails internals related to this. Incidentally, I'm not sure Rails handles this all that well from what I've seen so far, regardless of the delivery method. I've got more research to do on this.
