### ISSUE TITLE
Installing aws-sdk-rails causes version resolution issue

### ISSUE THREAD

**Issue by searls** [aws/aws-sdk-rails#111]
Following the documentation to set up SES v2 as my Action Mailer:

```ruby
config.action_mailer.delivery_method = :sesv2
```

Resulted in:

```
RuntimeError (Invalid delivery method :sesv2):
```

Digging in, I realized that Bundler had installed `3.1.0` from 2020 instead of the current `3.10.0` release, which predated the addition of the SES v2 mailer (as well as many other features). Attempting to run `bundle update` didn't change anything.

[I'm no stranger to this class of bug](https://github.com/standardrb/standard/issues/340), where an older release had more forgiving version resolution constraints results in users being served a confusingly/bewilderingly old version that doesn't work or match the README any more. I solved this by yanking older versions of standard which were at that point extremely out of date and no longer in much use. 

Anyway, in addition to the above issue, the hard deps in the gemspec result in this for me when I do pin the aws-sdk-rails version to `3.10.0`:

```
etching rack 2.2.8 (was 3.0.8)
Fetching aws-sdk-dynamodb 1.100.0
Fetching aws-sdk-sqs 1.69.0
Fetching aws-sdk-sesv2 1.43.0
Installing rack 2.2.8 (was 3.0.8)
Installing aws-sdk-dynamodb 1.100.0
Fetching aws-record 2.13.0
Fetching rack-session 1.0.2 (was 2.0.0)
Fetching aws-sessionstore-dynamodb 2.1.0
Fetching rackup 1.0.0 (was 2.1.0)
Installing aws-sdk-sqs 1.69.0
Installing aws-sdk-sesv2 1.43.0
Installing aws-record 2.13.0
Installing rack-session 1.0.2 (was 2.0.0)
Installing aws-sessionstore-dynamodb 2.1.0
Installing rackup 1.0.0 (was 2.1.0)
Fetching aws-sdk-rails 3.10.0 (was 3.1.0)
Installing aws-sdk-rails 3.10.0 (was 3.1.0)
Bundle complete! 27 Gemfile dependencies, 126 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Tracking this down, the culprit is the dynamodb gem, which has a hard dep on Rack 2:

```
aws-sessionstore-dynamodb (2.1.0)
      aws-sdk-dynamodb (~> 1, >= 1.85.0)
      rack (~> 2)
```

Giving up Rack 3 in order to adopt this gem for the SES integration in my Rails 7.1 app seems like a Bad Idea.

I actually only found the gem through lots of googling which actually landed me at this issue, which raised the challenges posed not only by the gem's name, but its wide surface area on other AWS dependencies: https://github.com/aws/aws-sdk-rails/issues/22

In that thread, @mullermp said:

> I would hope not. It's a decision that we made earlier last year. aws-sdk-rails will pull in extra AWS dependencies for its features. Rails itself might be considered "bloat" as it has many dependencies and features too. If you only need aws-sdk-ses you could install that gem instead and write a custom action mailer adapter similar to the one in aws-sdk-rails.

I definitely understand this sentiment, but because this gem is a toolkit of a half dozen different Rails integrations with Rails, each with potential version-constrained transitive dependencies on other things, using this gem seems to pose a pretty significant risk to keeping Rails (and one's other gems) up-to-date. For example, I only want to use the SES mailer functionality of the gem (so as to avoid SMTP), but because the gem also includes DynamoDB integration, even users who don't use DynamoDB will have to sacrifice Rack 3, which will eventually be required by Rails, which means a dependency on this gem could prevent upgrading Rails itself (to say nothing of Rack)

My advice would be to:

1. Start by documenting this issue in the README so other new users don't get thrown off, since Bundler will default to resolving to the very-old 3.1.0 for anyone who's on the latest version of Rails (currently 7.1.3).
2. Consider a release that either:
    a. Removes the hard dependency on the other AWS SDK gems, update the documentation to indicate that users should state the dependencies themselves, and instead detect whether those gems are installed and loadable at runtime (warning/erroring if the associated feature is configured and the gem is missing or an unsupported version)
    b. Spins this gem out into N gems—one per AWS feature—so that the surface area for end-users is constrained to only the features they need, reducing their dependency exposure (and associated security/support risks due to not being able to upgrade other dependencies)

I think 2(b) is probably closer to the "right" answer, even though it'd present more work. 2(a) is something I have done for plugin gems in the past but would be a breaking change for existing users and would require the gem to effectively manually do the job of version resolution insofar as validating the `Gem::Version` range matches your expectations at runtime

**Comment by mullermp** [comment]
Thanks for opening an issue and I'm sorry you ran into this. It appears [Rails 7.1](https://rubygems.org/gems/railties/versions/7.1.0) now depends on `rackup >= 1` which states a dependency on `rack >= 3`. There was ongoing work here: https://github.com/aws/aws-sessionstore-dynamodb-ruby/pull/33/files to upgrade the sessionstore gem to dynamodb. Given this upgrade is affecting customers, I think we can prioritize this to be higher.

As far as this gems strategy goes, we would like to keep `aws-sdk-rails` full of useful features but we can re-evaluate that decision. It was previously gem-ified in a few ways however we noticed adoption and discoverability of features was not great.

**Comment by mullermp** [comment]
Please take a look at https://github.com/aws/aws-sessionstore-dynamodb-ruby/pull/34 - I think this should unblock the upgrade for now.

**Comment by mullermp** [comment]
I've merged https://github.com/aws/aws-sessionstore-dynamodb-ruby/pull/34 to alleviate the issue. Please re-open if there is trouble.
