### ISSUE TITLE
Active Job logs are not output realtime to Cloudwatch logs on ECS fargate

### ISSUE THREAD

**Issue by shiino-shunsuke** [aws/aws-sdk-rails#112]
aws sqs active job is running in an ECS fargate environment.

A container is built using the dockerfile that comes standard with rails 7.1.1.

CMD in the dockerfile is overwritten with the "command" in the ECS task-definition, and aws_sqs_active_job is started with the following settings.

```
[
  "bundle",
  "exec",
  "aws_sqs_active_job",
  "--queue",
  "default"
]
```

At this time, logs that should have been output to Cloudwatch Logs via STDOUT were not output.

After that, logs were output to Cloudwatch Logs at the time the container was killed for deployment, etc.

We would like to see JOB logs in real time if possible.

A rails server running in a similar environment is able to check logs in cloudwatch logs in real time.

The following are the settings for aws sqs active job.

```
queues:
  default: 'https://sqs.xxx.amazonaws.com/xxxx/xxxx'
threads: 5
max_messages: 5
shutdown_timeout: 110
```

Is there any other way to configure the logs so that they can be viewed in real time?

version: 
    aws-sdk-rails (3.9.0)

**Comment by alextwoods** [comment]
Sorry you're running into this - you should be able to view job logs in real time!

In general, the default logging for the sqs active job poller/runner uses stdout, which should be picked up by the [awslogs fargate log driver](https://docs.aws.amazon.com/AmazonECS/latest/userguide/using_awslogs.html) in real time.

What rails logging config do you have for the rails server?

What are the environment settings for both tasks?  How do you have the awslogs driver [configured](https://docs.aws.amazon.com/AmazonECS/latest/userguide/using_awslogs.html#specify-log-config)?

**Comment by alextwoods** [comment]
What role(s) are you using? I believe you'll need `logs:CreateLogStream` and `logs:PutLogEvents` permission on the IAM role that you can launch your container instances with (though if this wasn't right, then I'm surprised you get the logs at shutdown).  

What launch type are you using? I think there are some additional considerations if you're using the EC2 launch type (eg: the AMI needs to support the awslogs driver).

**Comment by mullermp** [comment]
Is this logger being created as expected? Also shouldn't log_level be a symbol (`:debug`) or does it work as a string here? I agree with Alex that it should "just work" - it could be log misconfiguration somewhere..

```
  config.logger = ActiveSupport::Logger.new(STDOUT)
    .tap  { |logger| logger.formatter = ::Logger::Formatter.new }
    .then { |logger| ActiveSupport::TaggedLogging.new(logger) }

  config.log_level = ENV.fetch("RAILS_LOG_LEVEL", "debug")
```

**Comment by alextwoods** [comment]
Sorry we're still trying to reproduce this and figure out whats going on.

In the logs after termination, do you only get the one line?  Or do you get others (eg: `Polling on: <queue> => <url>` or `Processing batch of <n> messages)?
