### ISSUE TITLE
Aws::SES::Client Credentials are not refreshed

### ISSUE THREAD

**Issue by jufemaiz** [aws/aws-sdk-rails#12]
As a root cause of issues highlighted in https://github.com/aws/aws-sdk-rails/issues/11 Aws credentials are not being refreshed when using Aws::InstanceProfileCredentials.

My reading of the documentation is that Aws SDK should be rotating Aws::InstanceProfileCredentials automagically as required without manual intervention.

> If you're running your Ruby on Rails application on Amazon Elastic Compute Cloud, keep in mind that the AWS SDK for Ruby will automatically check Amazon EC2 instance metadata for credentials. 

http://docs.aws.amazon.com/sdkforruby/api/Aws/InstanceProfileCredentials.html
https://github.com/aws/aws-sdk-core-ruby/issues/193

**Comment by awood45** [comment]
I'm going to close this as a duplicate, and keep the discussion in the other issue.
