### ISSUE TITLE
V4 - Usage without ActiveStorage and ActiveMailbox enabled

### ISSUE THREAD

**Issue by davidwessman** [aws/aws-sdk-rails#133]
Hello!

We are using the gem for sending email via SES, but we do not have ActionMailbox or ActiveStorage loaded in the app.
On gem version 4.0.1 we therefore cannot load the app due to the error:

```ruby
Couldn't find Active Storage configuration in /home/runner/work/repo/config/storage.yml
```

Our `application.rb` starts like:

```ruby
require_relative "boot"

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
# require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
# require "action_mailbox/engine"
# require "action_text/engine"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
require "rails/test_unit/railtie"
```

Is there no way to use this gem unless you have ActionMailbox and ActiveStorage enabled?

**Comment by mullermp** [comment]
Thanks for opening an issue. I think that's the case currently and I'm open to suggestions for how to fix that. Was that also the case for ActiveStorage in version 3?

**Comment by davidwessman** [comment]
> Thanks for opening an issue. I think that's the case currently and I'm open to suggestions for how to fix that. Was that also the case for ActiveStorage in version 3?

We are currently using version 3 with no problems.

**Comment by mullermp** [comment]
I'm not able to reproduce this when I create a new rails app. I tried with both `require 'rails/all'` and with the requires you pasted above. I'm assuming your app was pretty old but then have upgraded it many times? What happens if you add a blank storage.yml file in config? Or at very least, define one for your test environment?

I'm assuming you ran into this because of the new ActionMailbox feature which uses ActiveStorage under the hood.

**Comment by davidwessman** [comment]
> I'm not able to reproduce this when I create a new rails app. I tried with both `require 'rails/all'` and with the requires you pasted above. I'm assuming your app was pretty old but then have upgraded it many times? What happens if you add a blank storage.yml file in config? Or at very least, define one for your test environment?
> 
> 
> 
> I'm assuming you ran into this because of the new ActionMailbox feature which uses ActiveStorage under the hood.

I am on vacation until mid August and will try to stay away from my work computer. Will get back to you.

**Comment by benjaminwols** [comment]
I've run into the same issue. We also don't require `active_storage` and `active_mailbox` in our app.

I've added a blank `storage.yml` file per your suggestion, but that runs into the next error:
`gems/activestorage-7.1.3.4/lib/active_storage/attached/model.rb:246:in `validate_global_service_configuration': Missing Active Storage service name. Specify Active Storage service name for config.active_storage.service in config/environments/development.rb (RuntimeError)`

I saw there is a PR #135 that addresses this. If you need me to test anything, please let me know.

**Comment by mullermp** [comment]
I'm currently looking at how to best check for this.

**Comment by mullermp** [comment]
I think the best thing I can really do is just check for ActionMailbox::Engine unless someone with more rails experience has a better option. Feel free to test that if you wish.

**Comment by mullermp** [comment]
I just pushed out version 4.0.2 that should fix this.
