### ISSUE TITLE
Sending Action mailer emails from different regions in the same application instance

### ISSUE THREAD

**Issue by kpalmvik** [aws/aws-sdk-rails#136]
Before version 4.0.2 (specifically https://github.com/aws/aws-sdk-rails/pull/131) it was possible to configure multiple Action mailer delivery methods with different configurations, such as:

```ruby
Aws::Rails.add_action_mailer_delivery_method(:east, credentials: creds, region: "us-east-1")
Aws::Rails.add_action_mailer_delivery_method(:west, credentials: creds, region: "us-west-1")
```

The result was a fallback to using `ses` (v1) for the two delivery methods `east` and `west`. You could then decide which delivery method, and thus region, to use when sending an email.

Because of the stricter validations added in 4.0.2, only `ses` and `sesv2` are now accepted as the first `name` argument.

Since defining two delivery methods this way is no longer possible I assume it is not (or has ever been?) the recommended way of setting up multiple delivery methods backed by SES.

However, from the existing documentation it is not obvious to me what the correct way would be, or if there is a completely different approach that is better suited for this.

Any suggestions?

**Comment by mullermp** [comment]
I'm very sorry I caused this, I actually did not imagine this use case. I can look to revert this behavior and make a note about improving this in a new MV.

**Comment by kpalmvik** [comment]
>I'm very sorry I caused this, I actually did not imagine this use case.

No worries at all. I believe it is the correct implementation and that we have simply been lucky that the fallback for unknown values worked.

>I can look to revert this behavior and make a note about improving this in a new MV.

From my side I would suggest that this is NOT reverted. Validating the configuration would is great.

But maybe it should be a deprecation warning until the next minor release?

Apart from that it would be great to have:

- clear documentation that only `ses` and `sesv2` are accepted values and that everything else will cause an exception.
- some configuration or escape hatch to handle this, probably unusual, case.

**Comment by mullermp** [comment]
I think that there should have been another parameter here for the mailer class. The name should be free-form (i.e. give me a foo mailer) and then mailer class either :ses or :sesv2 and validated.

I am not sure of any workaround for multiple regions. I am assuming you need multiple regions or is it just a nice to have?

**Comment by kpalmvik** [comment]
>The name should be free-form (i.e. give me a foo mailer) and then mailer class either :ses or :sesv2 and validated.

Yes, this would probably have been my first assumption on how to use generic action mailer delivery gem.

>I am assuming you need multiple regions or is it just a nice to have?

I'm honestly entirely sure if it is a strict requirement for us still, but I believe it is a valid use case generally as [described in this AWS blog post](https://aws.amazon.com/blogs/messaging-and-targeting/how-to-use-domain-with-amazon-ses-in-multiple-accounts-or-regions/):

>Other use-cases include customers who want to setup multi-region redundancy, need to satisfy data residency requirements, or need to send emails on behalf of several different clients. In all of these cases, customers can use different regions, in the same or across different accounts.

But perhaps this should ideally be handled by multiple application instances running in the respective region? Then it would be trivial to give them different configurations per region.

**Comment by mullermp** [comment]
Yeah, this method existed prior to :sesv2 being added, hence the original branch that you were defaulting to. The multi-region case you pointed out is valid. I think the best option here is to revert and on next major version do this correctly.
