### ISSUE TITLE
Feature Request: ActiveSupport Notifications

### ISSUE THREAD

**Issue by guyisra** [aws/aws-sdk-rails#14]
Hi,

In the current aws-sdk-rails and in aws-sdk-ruby there is no instrumentation support (unless I've missed it?) 

Is it possible to publish an ActiveSupport::Notification for every AWS call so we can subscribe to these events?

thanks

**Comment by awood45** [comment]
Can definitely take this as a feature request as we start investing in more features. Instrumentation support is something on our roadmap for this year, and this is one possible route.

**Comment by sivagollapalli** [comment]
Hi, I can take a look into this feature request if anyone could provide guidance about where to start and end goal?

**Comment by mullermp** [comment]
Hi @sivagollapalli, thanks for your interest. It looks like the original request was to publish an ActiveSupport notification whenever the SDK is invoked. I'm not sure how you would go about that without taking a look myself. Another use case (not mentioned) might be to have an ActiveSupport::SNS notification of some sort.

As a user of `aws-sdk-rails` what kinds of features would you like to see?

**Comment by sivagollapalli** [comment]
@mullermp Frankly speaking I don't know the use cases of this feature 😄 . In my opinion lets add instrumentation for one or two popular services like s3 or Ec2 and check how developers are using this and then establish to remaining services. let me know your thoughts.

**Comment by mullermp** [comment]
ActiveSupport has a guide here: https://edgeguides.rubyonrails.org/active_support_instrumentation.html#creating-custom-events

I think that we can instrument every client call, perhaps with "<service-name>.<operation>"  (ex: "s3.list_buckets")

My thought is that we should be agnostic to any client for this to be feature complete. The part that is missing (and requires investigation) would be how to detect calls to any of the Aws clients.

**Comment by sivagollapalli** [comment]
@mullermp Ok. let me do some investigation.
