### ISSUE TITLE
Clarification on how to use SES as Delivery Method

### ISSUE THREAD

**Issue by rodriguevara** [aws/aws-sdk-rails#141]
Hi there, I currently use smtp as ActionMailer delivery method, with `config.action_mailer.delivery_method = :smtp` and the corresponding `config.action_mailer.smtp_settings = {...` in my `application.rb`. In order to switch to the SES API, the only thing I need to do is change the delivery method to `config.action_mailer.delivery_method = :ses`? That's it? I have my AWS credentials and region as ENV variables in my `applitacion.yml`

Thanks in advance

**Comment by jterapin** [comment]
Hi! Yes, that is correct on the app-side.

For [additional context](https://docs.aws.amazon.com/sdk-for-ruby/aws-sdk-rails/api/Aws/Rails/SesMailer.html):
> Provides a delivery method for ActionMailer that uses Amazon Simple Email Service.
> Once you have an SES delivery method you can configure Rails to use this for ActionMailer in your environment configuration (e.g. RAILS_ROOT/config/environments/production.rb)
```
config.action_mailer.delivery_method = :ses
```
> Uses the AWS SDK for Ruby’s credential provider chain when creating an SES client instance.

I'm not sure how far along are you with setting up SES on your end but I will include this link, [Creating and verifying identities in Amazon SES](https://docs.aws.amazon.com/ses/latest/dg/creating-identities.html) to get started. Hope this helps.
