### ISSUE TITLE
Proposal: Extract eager loader into lightweight dependency

### ISSUE THREAD

**Issue by Schwad** [aws/aws-sdk-rails#143]
Ref: https://github.com/aws/aws-sdk-rails/pull/140

We'd like to use the eager loading in `aws-sdk-rails` for production use of `aws` gems. However we don't want to bring in the [full collection of runtime dependencies](https://github.com/aws/aws-sdk-rails/blob/main/aws-sdk-rails.gemspec#L21-L29) in this gem into our application.

Would it be possible to extract the railtie autoloading functionality into a small, lightweight gem? `aws-sdk-rails` could depend on it, and then `aws-sdk-ruby` users could also depend on it directly for eagerloading.

I [wrote a gem extraction for this this morning](https://github.com/schwad/aws-sdk-rails-eagerloader) if that helps. You are free to all the code (plus the core 'eager loading' was taken from the referenced PR). I tested the gem against our setup this morning.

cc @alextwoods

**Comment by mullermp** [comment]
I'm working on pulling the big features out of this gem and putting those into their own gems. The consequences of this is that eager loading would remain in this gem (I think it belongs here and not be extracted), but it should achieve your goal without moving that part out because all the other stuff would be.

**Comment by Schwad** [comment]
Yeah; I think for me (this isn't saying this applies to most people) if I can go from directly using 

`aws-sdk-s3`

To also using

`aws-sdk-s3`
`aws-sdk-rails`

And none of my experience/migration changes, except I now get eagerloading, that works great.

**Comment by mullermp** [comment]
This should be done with aws-sdk-rails ~> 5. I've refactored all of the features into their own gems. aws-sdk-rails ~> 4 will include those gems by default to avoid breaking changes but aws-sdk-rails ~5 will require adding the dependencies.
