### ISSUE TITLE
How to provide settings to `config.action_mailer.delivery_method`

### ISSUE THREAD

**Issue by nasmorn** [aws/aws-sdk-rails#150]
If I provide settings like

```
config.action_mailer.delivery_method = :sesv2, { region: ENV.fetch("AWS_REGION", nil), credentials: Aws::AssumeRoleCredentials.new(
      client:            Aws::STS::Client.new,
      role_arn:          "arn:aws:iam::XXXX:role/ROLENAME",
      role_session_name: "ses-session",
    ) }
```

I get this error.

```
gems/mail-2.8.1/lib/mail/message.rb:278:in `delivery_method': undefined method `new' for [:sesv2, {:region=>"eu-west-1", :credentials=>#<Aws::AssumeRoleCredentials
```

Thus I expect the initialisation has to work differently. I cannot find any examples though how the options get to the `Sesv2Mailer` class. This might not even be an issue specific to this library but maybe it is since rails exposes specific methods like `action_mailer.smtp_options`. Any explanation would be appreciated.

**Comment by mullermp** [comment]
I believe the README covers this case: https://github.com/aws/aws-sdk-rails?tab=readme-ov-file#override-credentials-or-other-client-options

Please re-open if there is still issue.

**Comment by nasmorn** [comment]
Thank you I must have overlooked that or aborted the search when I came to the part about testing. Appreciate the quick reply
