### ISSUE TITLE
Seems to not do RFC-2047 encoding

### ISSUE THREAD

**Issue by jeznag** [aws/aws-sdk-rails#16]
Hi, I'm using this gem to send emails via SES and am finding that it breaks when I use email addresses with non-ASCII characters. e.g.  用户@例子.广告

`Aws::SES::Errors::InvalidParameterValue (Local address contains control or whitespace):`

From the docs, it seems that the email address must be encoded according to RFC-2047. Is there a way to handle this case easily?

**Comment by awood45** [comment]
I need some more background to help you out, as I haven't heard of this issue before. Can you point me to the documentation you're referring to? I can go from there to try and reproduce this and point you to a workaround.

**Comment by awood45** [comment]
Nevermind, I [found the relevant documentation](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html).

Unfortunately, it does appear that the SDK is behavior correctly with regards to what the API expects. Essentially, that's an ASCII string, with that encoding already done. You'd need to sanitize your email inputs to be compliant before sending. Are there issues that make this especially difficult?

**Comment by jeznag** [comment]
Ok I'm not really sure how to do that. Can't seem to find any docs on using RFC-2047 encoding with action mailer. Linking to StackOverflow question in case someone comes across this issue via Google: https://stackoverflow.com/questions/44876345/action-mailer-with-international-email-addresses-rfc-2047

**Comment by mullermp** [comment]
I'm going to assume that this is solved?
