### ISSUE TITLE
nginx timeout for jobs that take more than 60 sec (default nginx timeout)

### ISSUE THREAD

**Issue by januszm** [aws/aws-sdk-rails#167]
I'm currently migrating from [Shoryuken](https://github.com/ruby-shoryuken/shoryuken) task queue (a [Sidekiq](https://github.com/sidekiq/sidekiq) clone that uses SQS as queue store) to AWS SDK Rails, and I've encountered a strange error. 
I mention Sidekiq because it's a de-facto state of the art task queue for Ruby world.
For longer jobs that require e.g. 5-10 minutes to complete, I get a timeout, and the message returns to the queue. It looks like the POST request to the application server is waiting for the task to complete, which is unacceptable for longer jobs, because some can take up to several hours. Am I doing something wrong, or is this software designed so that sqs daemon, when submitting a task to be executed using the POST method, waits for it to **complete**? I expected it to only wait for the task to be "**accepted**" for async execution, not for it to complete.

**Comment by alextwoods** [comment]
The fix has been merged and released in 5.1.0.

**Comment by januszm** [comment]
Amaz(on)ing! Thank you.
