### ISSUE TITLE
How to specify `configuration_set`

### ISSUE THREAD

**Issue by mikeover** [aws/aws-sdk-rails#18]
If I setup a Configuration Set for SES open/click notifications, how can I use it with this gem? Is that a config option that can be passed into `Aws::Rails.add_action_mailer_delivery_method`? Or even better, can it be specified in the mailer somewhere directly so I could potentially use different configuration sets based on the mailer?

**Comment by awood45** [comment]
Not sure, this sounds like a feature request. Can take a PR with ideas.

**Comment by mikeover** [comment]
Nevermind, found that I can just add the header in the mailers directly already.

**Comment by rromanchuk** [comment]
For people coming here from SEO in the future

Pseudo code example. The value is just the name of your config set.  PSA: to save yourself some debugging, if you have an IAM role, you might need to  configure some new actions

```ruby
class MyMailer < ActionMailer::Base
  after_action :set_config_list_headers
  
  def set_config_list_headers
    headers['X-SES-CONFIGURATION-SET'] = :my_config_set
  end
end
```
