### ISSUE TITLE
[Documentation] Credential configuration specific to client library - Using ec2 IAM roles

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-rails#19]
I prefer the method of not managing any access key/secrets as part of my deployment and this feature sounds fantastic, but was really hard to understand how to actually implement it. 

1. Create EC2 role with desired policies ✅ 
2. Attach IAM role to ec2 instance ✅ 
3. Configure `aws-sdk-rails` to use policy. ❓ 

Looking here, you can see a blurb for links with new information, but this is just general information, nothing to do with how to interact with this setup using the gem. 
http://docs.aws.amazon.com/sdk-for-ruby/v2/developer-guide/setup-config.html#aws-ruby-sdk-credentials-iam

After a bunch of digging i found 
`Aws::InstanceProfileCredentials.new.credentials.access_key_id` and `Aws::InstanceProfileCredentials.new.credentials.secret_access_key`  

Which now allows me to do the following: 

```ruby
Aws::Credentials.new(
                    Aws::InstanceProfileCredentials.new.credentials.access_key_id,
                    Aws::InstanceProfileCredentials.new.credentials.secret_access_key)
```

Is there any other convenience methods i'm missing?  It would be nice if the documentation gave implementation examples similar to the others (shared credentials, environment variables, etc)

**Comment by rromanchuk** [comment]
> Or maybe this? If you're running your Ruby on Rails application on Amazon Elastic Compute Cloud, keep in mind that the AWS SDK for Ruby will automatically check Amazon EC2 instance metadata for credentials. Learn more: IAM Roles for Amazon EC2

Just saw this, so maybe the answer is i have to do nothing at all?  I'll dig through the source, but how would one pass a credentials object to a third part that is expecting an instance of `Aws::Credentials`

**Comment by awood45** [comment]
That's correct, by default we pick up the credential provider chain, which will use EC2 Instance Metadata Credentials if present. The README example is for when you're not doing this and need to provide credentials manually.

In short: If you have an EC2 IAM role set up and want to use it, you don't have to do anything.

**Comment by rromanchuk** [comment]
@awood45 sweet!  Is there an easy getter for "what's my current credentials"

**Comment by rromanchuk** [comment]
Basically, how can i hand off these credentials to a third party gem like in this case? 

```ruby
if Rails.env.production? || Rails.env.staging?
  Chewy.settings = {
    host: 'blahblahblah.us-east-1.es.amazonaws.com:80',
    request_strategy: :sidekiq,
    transport_options: {
      headers: { content_type: 'application/json' },
      proc: -> (f) do
        f.request :aws_signers_v4,
                  service_name: 'es',
                  region: 'us-east-1',
                  credentials: Aws::Credentials.new(Rails.application.secrets.aws_access_key, Rails.application.secrets.aws_secret_key)
      end
    }
  }
end
```
