### ISSUE TITLE
how to lock down the aws-sdk version 

### ISSUE THREAD

**Issue by sburke56** [aws/aws-sdk-rails#2]
"This dependency will automatically pull in version 2 of the AWS SDK for Ruby."

What does this mean exactly?  How can I specify a version of the sdk.  Right now my gemfile looks like this.  Is that correct or is that going to lead to conflicts?  

```
gem 'aws-sdk', '2.2.8'
gem 'aws-sdk-rails', '1.0.0'
```

**Comment by awood45** [comment]
If you take a look at our [gemspec](https://github.com/aws/aws-sdk-rails/blob/master/aws-sdk-rails.gemspec), we depend on `aws-sdk-resources` major version 2.

Your gemfile is fine, no conflicts there. Mainly, that comment is there to avoid surprise - for example, SDK V1 users may wonder why the V2 packages are being pulled in.

Anyways, no problems with your configuration. You'll lock on that `aws-sdk` version (which in turn will lock the `aws-sdk-core` and `aws-sdk-resources` gem versions).
