### ISSUE TITLE
Rename to ses-mailer?

### ISSUE THREAD

**Issue by phstc** [aws/aws-sdk-rails#22]
I was Googling for "Action Mailer SES",  "SES Mailer Rails" etc, and I didn't find this gem - I found only [this one](https://github.com/drewblas/aws-ses), which apparently does not use the aws-sdk, therefore I don't want to use it.

It seems the only thing `aws-sdk-rails` does, is to implement the Action Mailer support for SES. With that, if this gem had a more specific name, it would be easier to find it and also reduce the time spent checking its code. I only wanted Action Mailer support, I didn't want anything different than that, since it could mess up with my current aws-sdk setup.

Any thoughts on renaming it or extracting it to a new repo?

**Comment by awood45** [comment]
Other than SEO factors, is there a reason you'd be concerned with using this gem?

Given that it's not transforming anything other than giving you the SES option and extra hooks for your credentials, I don't currently see a reason to extract the SES portion of the gem (and indeed that would break customers who use and rely on it).

**Comment by phstc** [comment]
Actually, it is not exactly because of SEO factors. I'm very careful to add new gems, I don't just add them, and `aws-sdk-rails` is a very generic name, feels like it would do more `aws-sdk` stuff, which I want to keep the control.  I only really wanted to use [this](https://github.com/aws/aws-sdk-rails/blob/master/lib/aws/rails/mailer.rb). 

For keeping avoid breaking changes, the mailer could be extracted to `ses-mailer` then this `aws-sdk-rails` could use it as a dependency, so no breaking changes, and this will leave the opportunity for `aws-sdk-rails` do more stuff, keeping `ses-mailer` specific for SES.

TBH just a more explicit description could be good enough  "This gem Only adds SES Action Mailer support".

**Comment by awood45** [comment]
I'll definitely keep this in mind if/when we expand what this gem does significantly, modularization would make sense if bloat is introduced. For now though, I don't see a reason to split this gem apart.

**Comment by phstc** [comment]
@awood45 sounds good. Thanks for the follow up 🍻

**Comment by Frexuz** [comment]
Is this not considered bloat? 😂  (Assuming we only want SES)

![Screenshot 2021-12-29 at 20 46 42](https://user-images.githubusercontent.com/49692/147663772-6bde2593-a68f-4948-af93-72dc2d220a72.png)

**Comment by mullermp** [comment]
I would hope not. It's a decision that we made earlier last year. `aws-sdk-rails` will pull in extra AWS dependencies for its features. Rails itself might be considered "bloat" as it has many dependencies and features too. If you only need `aws-sdk-ses` you could install that gem instead and write a custom action mailer adapter similar to the one in `aws-sdk-rails`.
