### ISSUE TITLE
rails logging level 

### ISSUE THREAD

**Issue by sburke56** [aws/aws-sdk-rails#3]
How do I set the logging level output for the aws calls?  Are they only setup to go to the debug level?

**Comment by awood45** [comment]
All AWS SDK log lines will come out at the same log level, but it is configurable. By default, it is `:debug`.

You could also use:
```ruby
Aws.config[:log_level] = :info
Aws.config[:log_level] = :warn
Aws.config[:log_level] = :error
Aws.config[:log_level] = :fatal
```

**Comment by awood45** [comment]
Keep in mind that I would not recommend using warn/error/fatal log levels with the AWS SDK logger, since, again, ALL log statements, many of which are debug/info level, will be output at the same log level.

**Comment by sburke56** [comment]
Awesome thanks for the info.
