### ISSUE TITLE
Cannot override region in config/environments/*.rb

### ISSUE THREAD

**Issue by stefanrendevski** [aws/aws-sdk-rails#30]
If i don't set AWS_REGION as an env variable, and pass it manually instead like: 
```
Aws::Rails.add_action_mailer_delivery_method(
  :ses,
  credentials: creds,
  region: 'us-east-1'
)
```

Whenever I try to send an email, i receive the following error: Aws::Errors::MissingRegionError. According to the documentation, this should be working.

Edit:

In fact, I cannot override the credentials either. If I have no AWS credentials in Rails.credentials, then the SES client seems to be instantiated with nil credentials, and every email attempt fails with: Aws::SES::Errors::SignatureDoesNotMatch

**Comment by mullermp** [comment]
What version of Rails and aws-sdk-rails are you using? I'm not able to reproduce this using Rails 6 and aws-sdk-rails 3.0.5. Are you calling the `add_action_mailer_delivery_method` method in an initializer or in an environments file?

The setup should be -

Environment:
`config.action_mailer.delivery_method = :ses`

Initializer:
```
Aws::Rails.add_action_mailer_delivery_method(
  :ses,
  credentials: creds,
  region: 'us-east-1'
)
```

In my case, I have no verified email addresses in us-east-1, so I correctly see `The following identities failed the check in region US-EAST-1: mamuller@amazon.com`. I have ~/.aws/config with us-west-2, so it should be properly overriding.

**Comment by stefanrendevski** [comment]
Oh I see, I was trying `Aws::Rails.add_action_mailer_delivery_method` in the environment file. I didn't know that doesn't work. Thank you for the quick reply.
