### ISSUE TITLE
Prefix with table name in `Aws :: Record`

### ISSUE THREAD

**Issue by yubele** [aws/aws-sdk-rails#62]
Hey everyone! This gem is great so I'm using it. 

However, in my environment, prefix is added to the dynamodb table for each environment.
Are you planning to add the ability to prefix the table name? (Please let me know if you have already added it.)
Would you accept pull requests?

Thanks!

**Comment by mullermp** [comment]
Hello. Thank you for using our gem. Yes we take pull requests.

Is this an issue with aws-record specifically? If so then this feature request belongs in: https://github.com/aws/aws-sdk-ruby-record

What do you mean by "prefix is added to the dynamodb table for each environment"? You can set the table name to whatever you'd like: https://docs.aws.amazon.com/sdk-for-ruby/aws-record/api/Aws/Record/RecordClassMethods.html#set_table_name-instance_method

**Comment by y-abe-seesaa** [comment]
My problem seemed to be solved using `set_table_name`.

Thank you for your quick support.

**Comment by yubele** [comment]
@mullermp
My problem seemed to be solved using set_table_name.

Thank you for your quick support.
