### ISSUE TITLE
DynamoDB Local support

### ISSUE THREAD

**Issue by thomaswitt** [aws/aws-sdk-rails#63]
Hi,

for testing purposes I can't find a possibility to configure host and port of the database in order to use [AWS' DynamoDB Local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html). In [Dynamoid](https://github.com/Dynamoid/dynamoid), I can easily configure an endpoint: `config.endpoint = 'http://localhost:8000'`

How to configure that with aws-sdk-rails?

**Comment by alextwoods** [comment]
Hey - you should be able to configure the `endpoint` of the client used for `aws-record` with the [Record.configure_client method](https://docs.aws.amazon.com/sdk-for-ruby/aws-record/api/Aws/Record/RecordClassMethods.html#configure_client-instance_method).

If you have an aws-record class, `MyRecord` then you should be able to do something like:
```
MyRecord.configure_client(endpoint: 'http://localhost:8000')
```

**Comment by thomaswitt** [comment]
@alextwoods Thanks for the idea! But - how do I do it if I just want to use aws-sdk-rails for storing my sessions in DynamoDB, no aws-record classes?

**Comment by mullermp** [comment]
Hey @thomaswitt, it should be supported by passing a client into the `dynamo_db_client` config.

[Documentation for dynamodb sessions](https://docs.aws.amazon.com/sdk-for-ruby/aws-sessionstore-dynamodb/api/Aws/SessionStore/DynamoDB/Configuration.html)

[Client generation code](https://github.com/aws/aws-sessionstore-dynamodb-ruby/blob/main/lib/aws/session_store/dynamo_db/configuration.rb#L197)

Creating your client:
```
dynamodb = Aws::DynamoDB::Client.new(endpoint: 'http://localhost:8000')
```

Then pass to your initializer. Check out the [Rails DynamoDB session store configuration README](https://github.com/aws/aws-sdk-rails#dynamodb-session-store).

**Comment by thomaswitt** [comment]
@mullermp Thanks a lot! As an idea, maybe you want to mention DynamoDB local and how to use it in your README?
