### ISSUE TITLE
Assuming role with temporary credentials timeout occurs.

### ISSUE THREAD

**Issue by heineman-bob** [aws/aws-sdk-rails#7]
While leveraging sts to assume a role and provide temp credentials to Aws.config[:credentials] inside the initializers as stated in this [guide](https://ruby.awsblog.com/post/Tx18J68KPIUWMOX/Announcing-the-aws-sdk-rails-Gem).  I am able to call AWS (SES) to send emails until the credentials expire.  After that I receive 403 errors.  Should I not be setting my credentials in my initializer file?  I attempted to bring the functionality into my ActionMailer base class to attempt to grab new credentials but did not succeed.  

Is there some obvious thing I am missing?  I am not a rails expert so if there is an obvious fix please forgive my lack of experience.

My initializer file.  I understand why this times out but how do I retreive new credentials for role?  
```

sts = Aws::STS::Client.new
role = sts.assume_role(role_arn: ENV['ROLE_ARN'],
                       role_session_name: format(
                         '%{appname}_%{stage}',
                          appname: ENV['APP_NAME'],
                          stage: ENV['RACK_ENV']),
                       duration_seconds: 900)

Aws.config[:credentials] = Aws::Credentials.new(
  role.credentials.access_key_id,
  role.credentials.secret_access_key,
  role.credentials.session_token)
```

**Comment by awood45** [comment]
Absolutely a fair question! The AWS SDK for Ruby provides a helper class that will refresh credentials on your behalf: [Aws::AssumeRoleCredentials](http://docs.aws.amazon.com/sdkforruby/api/Aws/AssumeRoleCredentials.html)

If you instantiate an instance of that class, and provide that as your credentials, you should no longer see 403 issues.

**Comment by awood45** [comment]
Confirmed this is working through other channels. Thanks!

**Comment by heineman-bob** [comment]
Thanks for the info!
