### ISSUE TITLE
This gem depends on more SDKs then documented

### ISSUE THREAD

**Issue by nerixim** [aws/aws-sdk-rails#73]
Hi.
https://github.com/aws/aws-sdk-rails#installation mentions this gem depending on SES SDK but as for version 3.6.1 it also depends on SQS and DynamoDB Session Storage gems.
Personally, I'm only using SES so removing dependencies except SES would work best but updating readme would suffice.

Regards and thanks for your work.

**Comment by mullermp** [comment]
Thanks for reporting. I've updated the README.

**Comment by mullermp** [comment]
Can't remove the dependencies from the gemspec because we have features that support it.
