### ISSUE TITLE
DynamoDB Session Store does not work with Rails 7

### ISSUE THREAD

**Issue by osyoyu** [aws/aws-sdk-rails#76]
DynamoDB Session Store (dynamodb_store) does not work with Rails 7.

The most simple setup (a fresh Rails 7.0.1 project with an empty action) would generate the following error:

```
NoMethodError (undefined method `enabled?' for {"_csrf_token"=>"..."}:Rack::Session::Abstract::SessionHash):

actionpack (7.0.1) lib/action_dispatch/middleware/flash.rb:62:in `commit_flash'
actionpack (7.0.1) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (7.0.1) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.1) lib/action_dispatch/routing/route_set.rb:850:in `call'
(snip)
```

The direct trigger is this change https://github.com/rails/rails/commit/ca7c820c6962788d510c99a68e725de83cbe9cad which accesses [`session.enabled?`](https://github.com/rails/rails/blob/v7.0.1/actionpack/lib/action_dispatch/request/session.rb#L87-L89) in the request dispatching.

However, the root cause seems to lie in dynamodb_store's implementation. When dynamodb_store is used, the `session` variable is a Rack::Session::Abstract::SessionHash, where it should be a ActionDispatch::Request::Session. `session.enabled?` is implemented only in ActionDispatch::Request::Session, thus resulting in the NoMethodError.

**Comment by mullermp** [comment]
Thanks for reporting this. We will investigate this.
