### ISSUE TITLE
Default `visibility_timeout` does not pick up the value from the SQS Queue in AWS

### ISSUE THREAD

**Issue by jshah** [aws/aws-sdk-rails#84]
Currently, the `visibility_timeout` defaults to 60 seconds in `poller.rb` and 120 seconds in `configuration.rb` (this is confusing in its own right) but I would expect the default to be what we set on the SQS queue directly in AWS.

Setting the `visibility_timeout` on the SQS queue gives the assumption that all messages would follow the `visibility_timeout` from the SQS queue, not from the workers. 

1. Could I get more information on why that decision was made and if we could update to have the default pulled from the SQS queue directly?
2. Can we update the defaults from `poller.rb` and `configuration.rb` for the `visibility_timeout` to be the same?

Thanks and please let me know if you need more information

**Comment by alextwoods** [comment]
Thanks for opening this - I agree the conflicting default settings in poller and configuration don't make sense and that we should instead prefer to use the `visability_timeout` from the queue (unless explicitly specified by the user). 

I'll take this as a feature request.
