### ISSUE TITLE
Region Mismatch

### ISSUE THREAD

**Issue by Brotakuu** [aws/aws-sdk-rails#9]
For anyone having issues with sending, you might want to check the region is correctly set. You can manually add the environment variable `AWS_REGION` to set it.  This might be useful information in the readme.

**Comment by awood45** [comment]
Going to interpret this as a need for clearer documentation around that part.

**Comment by awood45** [comment]
Does look like this is called out in the README, it's also worth nothing that you can set the region via configuration within code, if that's preferred.
