### ISSUE TITLE
Sender name gets dropped from email_from when using SESv2

### ISSUE THREAD

**Issue by sgomez17** [aws/aws-sdk-rails#97]
Following the introduction of SESV2, we have noticed that the name part of the sender gets dropped when using SESV2 when then email is sent.
So if the email comes from `Some Name <some.name@test.com>`, the recipient only sees the email address 'some.name@test.com>', but the 'Some Name' part is dropped.
We tested the same email with SES (v1), and that works ok and the email is received with both parts of the sender email (name + address).

**Comment by sgomez17** [comment]
Upon further investigation I can see that none of the :from methods from Mail::Message expose the name part of the sender, only the address.
![image](https://user-images.githubusercontent.com/33270615/213367863-bf8e1c8d-5e38-4051-ae5a-c87be1a54a2a.png)

However the header does contain the name.
![image](https://user-images.githubusercontent.com/33270615/213368423-41bf9cf3-88cf-46ba-822e-f835fb1e6498.png)

Maybe this is why in rails they extended the Mail::Message class from Rails6, as shown here: https://github.com/rails/rails/blob/ade27e5028ccbaaa5db8d966500844017925a751/actionmailbox/lib/action_mailbox/mail_ext/addresses.rb

We could introduce a check for mailer_sesv2.rb, if message responds to :from_address then use it, otherwise use the current value, as suggested in the first part of #93. Thoughts? I'm happy to create a PR for this.

**Comment by mullermp** [comment]
I think that makes sense. If you start a PR, I can help shepherd it out. I'll be on leave for a few months very soon - we can try to get this fixed before I go.

**Comment by mullermp** [comment]
Just to clarify, does this work for SESv1 *in the most recent aws-sdk-rails version*? Both implementations appear to be the same.

**Comment by sgomez17** [comment]
Yes, in the most recent version of this gem, I tried with :ses and :sesv2. Here are the message details for both emails, you can see the SESv2 version is missing the sender name:
![image](https://user-images.githubusercontent.com/33270615/213569758-da6b76f2-76fc-4aab-b0df-5870dc3c4765.png)

**Comment by alextwoods** [comment]
The PR has been merged and the fix has been released as part of 3.7.0.
